spring.application.name=Execution Service

server.port=${APP_PORT:8081}

# Database connection properties
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/execution_service_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:qwerty321}

microservice.is-producer=true
spring.kafka.consumer.group-id=execution-service
