CREATE TABLE queued_event (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	topic VARCHAR(100) NOT NULL,
	key VARCHAR(50) NOT NULL,
 	payload_class_name TEXT NOT NULL,
	payload TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT NOW(),
	is_delivered BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX idx_queued_event_delivered ON queued_event(is_delivered, created_at);

CREATE TABLE processed_event (
	topic VARCHAR(100) NOT NULL,
	event_id INTEGER NOT NULL,
	processed_at TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY(topic, event_id)
);

CREATE TABLE client (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE executor (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	remote_id INTEGER UNIQUE,
	version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE offering (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	remote_id INTEGER UNIQUE NOT NULL,
	cost DECIMAL(10, 2) NOT NULL,
	is_deprecated BOOLEAN NOT NULL DEFAULT false,
	version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE "order" (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	status VARCHAR(25) NOT NULL,
	id_client INTEGER NOT NULL REFERENCES client(id),
	id_offering INTEGER NOT NULL REFERENCES offering(id),
	cost DECIMAL(10, 2) NOT NULL,
	id_executor INTEGER REFERENCES executor(id),
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	deadline_on DATE NOT NULL,
	version INTEGER NOT NULL DEFAULT 0
);

----------Initialize contents----------

insert into client(name) values('Виталий');
insert into offering(remote_id, name, cost) values (1, 'Типовой расчёт', 20.40);
insert into offering(remote_id, name, cost) values (2, 'Курсовой проект', 250);
