CREATE TABLE queued_event (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	topic VARCHAR(100) NOT NULL,
	key VARCHAR(50) NOT NULL,
 	payload_class_name TEXT NOT NULL,
	payload TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	is_delivered BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX idx_queued_event_delivered ON queued_event(is_delivered, created_at);

CREATE TABLE processed_event (
	topic VARCHAR(100) NOT NULL,
	event_id INTEGER NOT NULL,
	processed_at TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY(topic, event_id)
);

CREATE TABLE client (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	remote_id INTEGER UNIQUE,
	version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE executor (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	final_date DATE,
	version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE offering (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	cost DECIMAL(10, 2) NOT NULL,
	points INTEGER NOT NULL,
	deprecated_at TIMESTAMP,
	version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE execution (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	status VARCHAR(25) NOT NULL,
	id_client INTEGER NOT NULL REFERENCES client(id),
	order_id INTEGER UNIQUE,
	id_offering INTEGER NOT NULL REFERENCES offering(id),
	cost DECIMAL(10, 2) NOT NULL,
	id_executor INTEGER REFERENCES executor(id),
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	deadline_on DATE NOT NULL,
	version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE execution_item (
	id_execution INTEGER NOT NULL REFERENCES execution(id),
	points INTEGER NOT NULL,
	date DATE NOT NULL,
	PRIMARY KEY(id_execution, date)
);

CREATE TABLE executor_stats (
	id_executor INTEGER PRIMARY KEY REFERENCES executor(id),
	daily_points INTEGER NOT NULL,
	active_executions_count INTEGER NOT NULL DEFAULT 0,
	version INTEGER NOT NULL DEFAULT 0
);

----------Initialize contents----------

insert into offering(name, cost, points) values ('Типовой расчёт', 80.40, 300);
insert into offering(name, cost, points) values ('Курсовой проект', 250, 1000);

insert into executor(name) values ('Иван');
insert into executor_stats(id_executor, daily_points) values (1, 350);
