spring.application.name=Payment Service

server.port=${APP_PORT:8082}
payment-system.failure-rate=${FAILURE_RATE:0.3}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_service_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:qwerty321}

microservice.is-producer=true
spring.kafka.consumer.group-id=payment-service
